python src/baseline/runner.py \
    --model_name roberta-base \
    --epochs 10 \
    --k_folds 5 \
    --rolling_k 3 \
    --early_stop_patience 3 \
    --freeze_epochs 3 \
    --train_path dataset/atsa/laptop14/train.json \
    --test_path dataset/atsa/laptop14/test.json \
    --val_path dataset/atsa/laptop14/val.json \
    --fusion_method concat